# Generated by Django 5.1.3 on 2024-11-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=255, unique=True)),
                ('checkout_request_id', models.CharField(max_length=255, unique=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('result_code', models.IntegerField()),
                ('result_desc', models.TextField()),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
