# Generated by Django 5.1.3 on 2024-11-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mpesa', '0002_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
