# Generated by Django 5.1.3 on 2024-12-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_video_url"),
    ]

    operations = []
