# Generated by Django 5.1.3 on 2024-12-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_clear_tiktok_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TikTok",
        ),
    ]
