# Generated by Django 5.1.3 on 2024-12-03 11:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_delete_tiktok"),
    ]

    operations = [
        migrations.CreateModel(
            name="TikTok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="video"
                    ),
                ),
                ("caption", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "TikTok",
                "verbose_name_plural": "TikTok",
            },
        ),
    ]
