# Generated by Django 5.1.3 on 2024-12-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_tiktok"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offer_end_data",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="offer_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="on_offer",
            field=models.BooleanField(default=False),
        ),
    ]
