# Generated by Django 5.1.3 on 2024-12-04 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_product_offer_end_data_product_offer_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="offer_end_data",
            new_name="offer_end_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="offer_price",
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
