# Generated by Django 5.1.3 on 2024-12-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_offer_end_data_product_offer_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="offer_end_date",
            new_name="discount_end_date",
        ),
    ]
