# Generated by Django 4.1.3 on 2024-11-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
