# Generated by Django 5.1.3 on 2024-12-04 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=4,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.1),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
