# Generated by Django 4.1.3 on 2024-11-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_deliveryoption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryOption',
            new_name='DeliveryOptions',
        ),
    ]
