# Generated by Django 5.1.3 on 2024-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_product_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="author",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogs",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
