# Generated by Django 4.1.3 on 2024-11-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_deliveryoption_deliveryoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoptions',
            name='value',
        ),
    ]
