# Generated by Django 5.1.3 on 2024-11-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_deliveryoptions_options_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('primary_number', models.IntegerField()),
                ('secondary_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=200)),
                ('amount_paid', models.IntegerField()),
                ('transaction_code', models.CharField(max_length=200)),
                ('delivery_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
