# Generated by Django 5.1.3 on 2024-11-26 03:32

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_deliveries"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("sub_title", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="deliveries",
            options={"verbose_name": "Delivery", "verbose_name_plural": "Deliveries"},
        ),
        migrations.RenameField(
            model_name="deliveries",
            old_name="transaction_code",
            new_name="mpesa_transaction_code",
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="api.brand",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=4,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
