# Generated by Django 5.1.3 on 2024-12-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_blog_alter_hero_options_hero_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="sub_title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
