# Generated by Django 5.1.3 on 2024-12-02 10:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_blog_sub_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                default="", max_length=255, verbose_name="thumbnail"
            ),
            preserve_default=False,
        ),
    ]
