# Generated by Django 5.1.3 on 2024-12-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_blog_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
