# Generated by Django 5.1.3 on 2024-12-03 06:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_blogs_delete_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TikTok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_link", models.URLField(max_length=355)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("caption", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "TikTok",
                "verbose_name_plural": "TikTok",
            },
        ),
        migrations.AlterField(
            model_name="blogs",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
