# Generated by Django 5.1.3 on 2024-12-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_tiktok_alter_blogs_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tiktok",
            old_name="video_link",
            new_name="video_url",
        ),
        migrations.AddField(
            model_name="tiktok",
            name="embedded_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tiktok",
            name="caption",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
